// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClaXnXJ9nTb2sRssowNlHbXT9jXAi9JVY',
    appId: '1:852135500460:web:03f0743f694b22a5699d09',
    messagingSenderId: '852135500460',
    projectId: 'vendini-337ac',
    authDomain: 'vendini-337ac.firebaseapp.com',
    storageBucket: 'vendini-337ac.firebasestorage.app',
    measurementId: 'G-8TJXTQ7KK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqKKwGWrYG6h-bul7TY5bUdXdYMXmKtI',
    appId: '1:852135500460:android:cbb6477ca9b492ee699d09',
    messagingSenderId: '852135500460',
    projectId: 'vendini-337ac',
    storageBucket: 'vendini-337ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_u3EuMxkIsmBwrrVPY2_nYPCbtyhfVY',
    appId: '1:852135500460:ios:9fdf8897187b426a699d09',
    messagingSenderId: '852135500460',
    projectId: 'vendini-337ac',
    storageBucket: 'vendini-337ac.firebasestorage.app',
    iosBundleId: 'com.example.vendini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_u3EuMxkIsmBwrrVPY2_nYPCbtyhfVY',
    appId: '1:852135500460:ios:9fdf8897187b426a699d09',
    messagingSenderId: '852135500460',
    projectId: 'vendini-337ac',
    storageBucket: 'vendini-337ac.firebasestorage.app',
    iosBundleId: 'com.example.vendini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClaXnXJ9nTb2sRssowNlHbXT9jXAi9JVY',
    appId: '1:852135500460:web:6e0c66a5cf1f2852699d09',
    messagingSenderId: '852135500460',
    projectId: 'vendini-337ac',
    authDomain: 'vendini-337ac.firebaseapp.com',
    storageBucket: 'vendini-337ac.firebasestorage.app',
    measurementId: 'G-KK816YWGX0',
  );
}
